repos:

# Automatic source code formatting
- repo: https://github.com/psf/black
  rev: 23.9.1
  hooks:
  - id: black
    args: [--safe, --quiet]

# Syntax check and some basic
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: check-ast

- repo: https://github.com/charliermarsh/ruff-pre-commit
  rev: v0.0.291
  hooks:
    - id: ruff
      args: ["--fix", "--show-fixes"]

